controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Redirection de la route racine (/) vers /transats
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: transat_index
        permanent: true
